# version: '3.8'

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: my_mongo
#     restart: always
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password
#     volumes:
#       - mongo_data:/data/db

#   mongo_express:
#     image: mongo-express:latest
#     container_name: mongo_express
#     restart: always
#     depends_on:
#       - mongodb
#     ports:
#       - "8081:8081"
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#       ME_CONFIG_MONGODB_ADMINPASSWORD: password
#       ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

# volumes:
#   mongo_data:
#     driver: local
# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: my_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: my_pgadmin
#     restart: always
#     depends_on:
#       - postgres
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: password
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin

# volumes:
#   postgres_data:
#     driver: local
#   pgadmin_data:
#     driver: local
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: petshop_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: petshop_pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  postgres_data:


